import type { CSSProperties } from "react";

/** Co-located styles for the eval case editor modal (longhand borders only). */
const field = {
  width: "100%",
  boxSizing: "border-box",
  padding: "10px 12px",
  borderRadius: 7,
  borderWidth: 1,
  borderStyle: "solid",
  borderColor: "var(--border-strong)",
  background: "var(--bg-elevated)",
  color: "var(--text-primary)",
  fontSize: 13,
} satisfies CSSProperties;

const pre = {
  margin: 0,
  padding: "12px 14px",
  fontFamily: "var(--font-mono, monospace)",
  fontSize: 12.5,
  lineHeight: 1.55,
  whiteSpace: "pre-wrap",
  overflowWrap: "anywhere",
  color: "var(--text-primary)",
} satisfies CSSProperties;

export const s = {
  body: { display: "grid", gridTemplateColumns: "minmax(0, 1fr) minmax(0, 1fr)", minHeight: 420 } satisfies CSSProperties,
  left: {
    padding: "16px 20px",
    display: "flex",
    flexDirection: "column",
    gap: 10,
    borderRightWidth: 1,
    borderRightStyle: "solid",
    borderRightColor: "var(--border)",
  } satisfies CSSProperties,
  right: { padding: "16px 20px", display: "flex", flexDirection: "column", gap: 10 } satisfies CSSProperties,
  label: { fontSize: 13, fontWeight: 600, color: "var(--text-secondary)" } satisfies CSSProperties,
  required: { color: "var(--crit)", marginLeft: 4 } satisfies CSSProperties,
  field,
  fieldInvalid: { ...field, borderColor: "var(--crit)" } satisfies CSSProperties,
  mono: { ...field, fontFamily: "var(--font-mono, monospace)", fontSize: 12.5 } satisfies CSSProperties,
  textarea: (invalid: boolean): CSSProperties => ({
    ...field,
    borderColor: invalid ? "var(--crit)" : "var(--border-strong)",
    fontFamily: "var(--font-mono, monospace)",
    fontSize: 12.5,
    lineHeight: 1.55,
    minHeight: 260,
    resize: "vertical",
  }),
  fieldHint: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  fieldError: { fontSize: 12, color: "var(--crit)" } satisfies CSSProperties,
  readOnlyBox: {
    minHeight: 220,
    maxHeight: 360,
    overflow: "auto",
    borderRadius: 7,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--border)",
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  pre,
  fileList: { margin: 0, padding: "12px 14px 12px 32px", fontFamily: "var(--font-mono, monospace)", fontSize: 12.5, overflowWrap: "anywhere" } satisfies CSSProperties,
  expectedHeader: { display: "flex", alignItems: "center", gap: 10 } satisfies CSSProperties,
  spacer: { flex: 1 } satisfies CSSProperties,
  badge: (ok: boolean): CSSProperties => ({
    fontSize: 12,
    fontWeight: 600,
    padding: "2px 8px",
    borderRadius: 6,
    color: ok ? "var(--ok)" : "var(--crit)",
  }),
  lastRun: (passed: boolean): CSSProperties => ({
    padding: "12px 14px",
    borderRadius: 8,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: passed ? "var(--ok)" : "var(--crit)",
    fontSize: 13,
    color: "var(--text-secondary)",
  }),
  lastRunTitle: { fontWeight: 700, color: "var(--text-primary)" } satisfies CSSProperties,
  alert: {
    padding: "10px 12px",
    borderRadius: 8,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--crit)",
    color: "var(--crit)",
    fontSize: 13,
    overflowWrap: "anywhere",
  } satisfies CSSProperties,
  footer: { display: "flex", alignItems: "center", gap: 8 } satisfies CSSProperties,
  runOnSave: { display: "inline-flex", alignItems: "center", gap: 8, fontSize: 13, color: "var(--text-secondary)", cursor: "pointer" } satisfies CSSProperties,
  state: { padding: 28, fontSize: 14, color: "var(--text-secondary)" } satisfies CSSProperties,
} as const;
