import type { CSSProperties } from "react";

/**
 * Co-located styles for ConventionCard. The accent stripe is set per side
 * (never `borderColor` + `borderLeftColor` together — React treats the former
 * as a shorthand and drops the stripe on re-render; see client/INSIGHTS.md).
 */
export const s = {
  card: (accepted: boolean, rejected: boolean): CSSProperties => ({
    opacity: rejected ? 0.7 : 1,
    display: "flex",
    gap: 18,
    padding: "16px 18px 14px 20px",
    borderRadius: 10,
    background: "var(--bg-elevated)",
    borderTop: "1px solid var(--border)",
    borderRight: "1px solid var(--border)",
    borderBottom: "1px solid var(--border)",
    borderLeft: `3px solid ${accepted ? "var(--ok)" : "var(--border-strong)"}`,
  }),
  main: { flex: 1, minWidth: 0, display: "flex", flexDirection: "column", gap: 10 } satisfies CSSProperties,
  titleRow: { display: "flex", alignItems: "center", gap: 8 } satisfies CSSProperties,
  rule: { fontSize: 15, fontWeight: 600, fontStyle: "italic", lineHeight: 1.4 } satisfies CSSProperties,
  evidence: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--code-bg)",
    overflow: "hidden",
  } satisfies CSSProperties,
  evidenceHeader: {
    display: "flex",
    alignItems: "center",
    padding: "6px 10px 6px 14px",
    borderBottom: "1px solid var(--border)",
  } satisfies CSSProperties,
  evidencePath: {
    flex: 1,
    minWidth: 0,
    fontSize: 12.5,
    color: "var(--text-secondary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  copyBtn: {
    background: "none",
    border: "none",
    cursor: "pointer",
    color: "var(--text-muted)",
    padding: 4,
    display: "grid",
    placeItems: "center",
  } satisfies CSSProperties,
  code: {
    margin: 0,
    padding: "10px 14px",
    fontSize: 12.5,
    lineHeight: 1.6,
    overflowX: "auto",
    whiteSpace: "pre",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  moreBtn: {
    alignSelf: "flex-start",
    display: "flex",
    alignItems: "center",
    gap: 4,
    background: "none",
    border: "none",
    cursor: "pointer",
    fontSize: 12,
    color: "var(--text-muted)",
    padding: 0,
  } satisfies CSSProperties,
  confidenceRow: { display: "flex", alignItems: "center", gap: 12 } satisfies CSSProperties,
  confidenceLabel: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  confidenceBar: { width: 130 } satisfies CSSProperties,
  confidenceValue: { fontSize: 12, color: "var(--text-secondary)" } satisfies CSSProperties,
  actions: { width: 150, flexShrink: 0, display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  editForm: { display: "flex", flexDirection: "column", gap: 10 } satisfies CSSProperties,
  fieldLabel: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    fontSize: 12,
    fontWeight: 500,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  ruleInput: {
    width: "100%",
    resize: "vertical",
    fontSize: 14,
    lineHeight: 1.45,
    padding: "8px 10px",
    borderRadius: 7,
    border: "1px solid var(--border-strong)",
    background: "var(--bg-surface)",
    color: "var(--text-primary)",
    outline: "none",
  } satisfies CSSProperties,
  editActions: { display: "flex", justifyContent: "flex-end", gap: 8 } satisfies CSSProperties,
} as const;
