import type { CSSProperties } from "react";

/** Co-located styles for the shared context-document picker. */
export const s = {
  header: { display: "flex", alignItems: "center", gap: 12, flexWrap: "wrap" } satisfies CSSProperties,
  title: { fontSize: 17, fontWeight: 700 } satisfies CSSProperties,
  hint: { fontSize: 13, color: "var(--text-muted)", margin: "10px 0 16px", lineHeight: 1.5 } satisfies CSSProperties,
  search: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "7px 11px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    width: 240,
    marginLeft: "auto",
  } satisfies CSSProperties,
  searchInput: {
    flex: 1,
    minWidth: 0,
    fontSize: 13,
    background: "transparent",
    border: "none",
    outline: "none",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  list: { display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  row: (attached: boolean, dropTarget: boolean, dragging: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "10px 14px",
    borderRadius: 8,
    border: "1px solid " + (dropTarget ? "var(--accent)" : "var(--border)"),
    background: attached ? "var(--bg-hover)" : "var(--bg-elevated)",
    opacity: dragging ? 0.55 : 1,
  }),
  handle: (active: boolean, grabbing: boolean): CSSProperties => ({
    color: active ? "var(--text-muted)" : "var(--border-strong)",
    cursor: active ? (grabbing ? "grabbing" : "grab") : "default",
    display: "inline-flex",
    flexShrink: 0,
    opacity: active ? 1 : 0.4,
    padding: 4,
    margin: -4,
    touchAction: active ? "none" : "auto",
  }),
  checkbox: { width: 16, height: 16, flexShrink: 0, accentColor: "var(--accent)" } satisfies CSSProperties,
  name: {
    fontSize: 14,
    fontWeight: 600,
    color: "var(--text-primary)",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    minWidth: 0,
  } satisfies CSSProperties,
  folder: { fontSize: 12, color: "var(--text-muted)", flexShrink: 0 } satisfies CSSProperties,
  spacer: { flex: 1 } satisfies CSSProperties,
  badge: (color: string): CSSProperties => ({
    fontSize: 11,
    fontWeight: 600,
    color,
    background: `color-mix(in srgb, ${color} 12%, transparent)`,
    padding: "2px 8px",
    borderRadius: 4,
    flexShrink: 0,
    whiteSpace: "nowrap",
  }),
  tokens: { fontSize: 12, color: "var(--text-muted)", flexShrink: 0 } satisfies CSSProperties,
  previewBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "5px 10px",
    borderRadius: 6,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    color: "var(--text-secondary)",
    fontSize: 12,
    cursor: "pointer",
    flexShrink: 0,
  } satisfies CSSProperties,
  footer: {
    display: "flex",
    alignItems: "center",
    gap: 16,
    flexWrap: "wrap",
    marginTop: 18,
    paddingTop: 14,
    borderTop: "1px solid var(--border)",
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  barTrack: {
    flex: "1 1 120px",
    minWidth: 120,
    height: 6,
    borderRadius: 3,
    background: "var(--bg-hover)",
    overflow: "hidden",
  } satisfies CSSProperties,
  barFill: (pct: number, over: boolean): CSSProperties => ({
    width: `${pct}%`,
    height: "100%",
    background: over ? "var(--warn)" : "var(--accent)",
  }),
  total: { fontWeight: 600, color: "var(--text-secondary)" } satisfies CSSProperties,
  warn: {
    marginTop: 12,
    padding: "8px 12px",
    borderRadius: 7,
    fontSize: 13,
    color: "var(--warn)",
    background: "var(--warn-bg)",
  } satisfies CSSProperties,
  alert: {
    marginTop: 12,
    padding: "8px 12px",
    borderRadius: 7,
    fontSize: 13,
    color: "var(--crit)",
    background: "var(--crit-bg)",
  } satisfies CSSProperties,
  notice: { fontSize: 13, color: "var(--text-muted)", margin: "0 0 12px" } satisfies CSSProperties,
  live: { fontSize: 12, color: "var(--text-muted)", minHeight: 16, marginTop: 8 } satisfies CSSProperties,
} as const;
