import type { CSSProperties } from "react";

/** Co-located styles for ImportSkillModal. */
export const s = {
  body: { padding: "18px 24px", display: "flex", flexDirection: "column", gap: 16 } satisfies CSSProperties,
  trust: {
    display: "flex",
    gap: 10,
    alignItems: "flex-start",
    fontSize: 13,
    lineHeight: 1.5,
    color: "var(--text-secondary)",
    padding: "10px 12px",
    borderRadius: 7,
    background: "var(--warn-bg)",
  } satisfies CSSProperties,
  drop: {
    position: "relative",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 8,
    padding: "36px 24px",
    borderRadius: 10,
    border: "1px dashed var(--border-strong)",
    background: "var(--bg-surface)",
    cursor: "pointer",
    textAlign: "center",
  } satisfies CSSProperties,
  dropTitle: { fontSize: 14, fontWeight: 600 } satisfies CSSProperties,
  dropHint: { fontSize: 12, color: "var(--text-muted)", maxWidth: 440, lineHeight: 1.45 } satisfies CSSProperties,
  fileInput: { position: "absolute", inset: 0, opacity: 0, cursor: "pointer" } satisfies CSSProperties,
  error: {
    fontSize: 13,
    color: "var(--crit)",
    padding: "10px 12px",
    borderRadius: 7,
    background: "var(--crit-bg)",
  } satisfies CSSProperties,
  warning: {
    display: "flex",
    gap: 8,
    alignItems: "center",
    fontSize: 13,
    color: "var(--warn)",
  } satisfies CSSProperties,
  sectionTitle: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    marginBottom: 8,
  } satisfies CSSProperties,
  ignored: { display: "flex", gap: 6, flexWrap: "wrap" } satisfies CSSProperties,
  columns: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 20 } satisfies CSSProperties,
  column: { minWidth: 0 } satisfies CSSProperties,
  markdown: {
    fontSize: 13.5,
    padding: "12px 14px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    maxHeight: 460,
    overflow: "auto",
  } satisfies CSSProperties,
  footer: { display: "flex", alignItems: "center", gap: 8 } satisfies CSSProperties,
} as const;
