import type { CSSProperties } from "react";

/** Co-located styles for RangeDialog. Borders are set per side (INSIGHTS: `borderColor` shorthand trap). */
export const s = {
  overlay: {
    position: "fixed",
    inset: 0,
    display: "grid",
    placeItems: "center",
    zIndex: 60,
    padding: 28,
    background: "rgba(0,0,0,0.5)",
  } satisfies CSSProperties,
  dialog: {
    width: 560,
    maxWidth: "100%",
    maxHeight: "92%",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    background: "var(--bg-elevated)",
    borderTop: "1px solid var(--border-strong)",
    borderRight: "1px solid var(--border-strong)",
    borderBottom: "1px solid var(--border-strong)",
    borderLeft: "1px solid var(--border-strong)",
    borderRadius: 14,
    boxShadow: "var(--shadow-modal)",
  } satisfies CSSProperties,
  header: {
    display: "flex",
    alignItems: "flex-start",
    gap: 14,
    padding: "16px 20px",
    borderBottom: "1px solid var(--border)",
  } satisfies CSSProperties,
  title: { flex: 1, margin: 0, fontSize: 16, fontWeight: 700 } satisfies CSSProperties,
  body: {
    flex: 1,
    overflow: "auto",
    padding: "16px 20px",
    display: "flex",
    flexDirection: "column",
    gap: 14,
  } satisfies CSSProperties,
  group: { margin: 0, padding: 0, border: "none", display: "flex", gap: 16, flexWrap: "wrap" } satisfies CSSProperties,
  option: { display: "inline-flex", alignItems: "center", gap: 6, fontSize: 13 } satisfies CSSProperties,
  marker: { fontSize: 11, fontWeight: 700, color: "var(--accent)" } satisfies CSSProperties,
  fields: { display: "flex", gap: 14 } satisfies CSSProperties,
  field: { display: "flex", flexDirection: "column", gap: 4, fontSize: 12, color: "var(--text-secondary)" } satisfies CSSProperties,
  input: {
    width: 110,
    padding: "6px 8px",
    fontSize: 13,
    fontFamily: "var(--font-mono, monospace)",
    color: "var(--text-primary)",
    background: "var(--bg-surface)",
    borderTop: "1px solid var(--border-strong)",
    borderRight: "1px solid var(--border-strong)",
    borderBottom: "1px solid var(--border-strong)",
    borderLeft: "1px solid var(--border-strong)",
    borderRadius: 6,
  } satisfies CSSProperties,
  reason: { margin: 0, paddingLeft: 18, fontSize: 12.5, color: "var(--text-secondary)" } satisfies CSSProperties,
  sectionHeading: { margin: "0 0 4px", fontSize: 12, fontWeight: 700, color: "var(--text-secondary)" } satisfies CSSProperties,
  preview: {
    margin: 0,
    padding: 0,
    listStyle: "none",
    maxHeight: 220,
    overflow: "auto",
    fontFamily: "var(--font-mono, monospace)",
    fontSize: 12,
    background: "var(--bg-surface)",
    borderTop: "1px solid var(--border)",
    borderRight: "1px solid var(--border)",
    borderBottom: "1px solid var(--border)",
    borderLeft: "1px solid var(--border)",
    borderRadius: 6,
  } satisfies CSSProperties,
  previewRow: { display: "flex", gap: 10, padding: "1px 8px" } satisfies CSSProperties,
  lineNo: { minWidth: 36, textAlign: "right", color: "var(--text-muted)", userSelect: "none" } satisfies CSSProperties,
  lineText: { whiteSpace: "pre", overflowWrap: "normal" } satisfies CSSProperties,
  muted: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  problem: { fontSize: 12, fontWeight: 600, color: "var(--crit)", overflowWrap: "anywhere" } satisfies CSSProperties,
  footer: {
    display: "flex",
    justifyContent: "flex-end",
    gap: 10,
    padding: "14px 20px",
    borderTop: "1px solid var(--border)",
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
} as const;
