import type { CSSProperties } from "react";

/** Co-located styles for BlastSymbolRow. */
export const s = {
  row: {
    borderRadius: 6,
    background: "var(--bg-elevated)",
    borderTopWidth: 1,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderLeftWidth: 1,
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: "var(--border)",
    borderRightColor: "var(--border)",
    borderBottomColor: "var(--border)",
    borderLeftColor: "var(--border)",
  } satisfies CSSProperties,
  toggle: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
    padding: "8px 10px",
    background: "none",
    border: "none",
    cursor: "pointer",
    textAlign: "left",
  } satisfies CSSProperties,
  chevron: (open: boolean): CSSProperties => ({
    color: "var(--text-muted)",
    transform: open ? "rotate(90deg)" : "none",
    transition: "transform 0.15s",
    flexShrink: 0,
  }),
  name: { fontFamily: "var(--font-mono, monospace)", fontSize: 13, color: "var(--text-primary)" } satisfies CSSProperties,
  count: { marginLeft: "auto", fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  body: { padding: "0 10px 10px 30px", display: "flex", flexDirection: "column", gap: 10 } satisfies CSSProperties,
  callers: { display: "flex", flexDirection: "column", gap: 4, margin: 0, padding: 0, listStyle: "none" } satisfies CSSProperties,
  caller: { display: "flex", alignItems: "center", gap: 6, fontSize: 12.5, minWidth: 0 } satisfies CSSProperties,
  callerIcon: { color: "var(--text-muted)", flexShrink: 0 } satisfies CSSProperties,
  callerRef: {
    fontFamily: "var(--font-mono, monospace)",
    fontSize: 12,
    color: "var(--text-secondary)",
    wordBreak: "break-all",
  } satisfies CSSProperties,
  callerLink: {
    fontFamily: "var(--font-mono, monospace)",
    fontSize: 12,
    color: "var(--accent, var(--text-primary))",
    textDecoration: "underline",
    wordBreak: "break-all",
  } satisfies CSSProperties,
  group: { display: "flex", flexDirection: "column", gap: 6 } satisfies CSSProperties,
  groupLabel: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  chips: { display: "flex", flexWrap: "wrap", gap: 6 } satisfies CSSProperties,
  chip: {
    fontFamily: "var(--font-mono, monospace)",
    fontSize: 11.5,
    padding: "2px 8px",
    borderRadius: 5,
    background: "var(--bg-hover)",
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  chipCron: {
    fontFamily: "var(--font-mono, monospace)",
    fontSize: 11.5,
    padding: "2px 8px",
    borderRadius: 5,
    background: "var(--warn-bg)",
    color: "var(--warn)",
  } satisfies CSSProperties,
} as const;
