import type { CSSProperties } from "react";

/** Co-located styles for BlastRadiusCard. Border sides are set explicitly (client INSIGHTS 2026-09-19). */
export const s = {
  card: { marginBottom: 4 } satisfies CSSProperties,
  errorText: { fontSize: 12.5, color: "var(--crit)", marginTop: 12, marginBottom: 0 } satisfies CSSProperties,
  degraded: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    padding: "10px 12px",
    marginBottom: 14,
    borderRadius: 6,
    background: "var(--warn-bg)",
    color: "var(--warn)",
    borderTopWidth: 1,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderLeftWidth: 3,
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: "var(--warn)",
    borderRightColor: "var(--warn)",
    borderBottomColor: "var(--warn)",
    borderLeftColor: "var(--warn)",
  } satisfies CSSProperties,
  degradedTitle: { display: "flex", alignItems: "center", gap: 6, fontSize: 13, fontWeight: 600 } satisfies CSSProperties,
  degradedReason: { fontSize: 12.5, margin: 0 } satisfies CSSProperties,
  degradedActions: { display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap" } satisfies CSSProperties,
  headerRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 14,
  } satisfies CSSProperties,
  viewSwitch: { display: "inline-flex" } satisfies CSSProperties,
  statsRow: { display: "flex", flexWrap: "wrap", gap: 8 } satisfies CSSProperties,
  stat: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    fontSize: 12.5,
    padding: "4px 10px",
    borderRadius: 6,
    background: "var(--bg-hover)",
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  statValue: { fontWeight: 700, color: "var(--text-primary)" } satisfies CSSProperties,
  viewButton: (active: boolean, first: boolean): CSSProperties => ({
    padding: "4px 12px",
    fontSize: 12.5,
    textTransform: "capitalize",
    cursor: "pointer",
    color: active ? "var(--accent)" : "var(--text-secondary)",
    background: active ? "var(--accent-bg)" : "transparent",
    borderTopWidth: 1,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderLeftWidth: 1,
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: active ? "var(--accent)" : "var(--border)",
    borderRightColor: active ? "var(--accent)" : "var(--border)",
    borderBottomColor: active ? "var(--accent)" : "var(--border)",
    borderLeftColor: active ? "var(--accent)" : "var(--border)",
    borderTopLeftRadius: first ? 6 : 0,
    borderBottomLeftRadius: first ? 6 : 0,
    borderTopRightRadius: first ? 0 : 6,
    borderBottomRightRadius: first ? 0 : 6,
    // The second button overlaps the first one's right border by 1px so the
    // shared edge is a single line; the active one is raised so its accent
    // border is never covered by a neighbour's grey one.
    marginLeft: first ? 0 : -1,
    position: "relative",
    zIndex: active ? 1 : 0,
  }),
  emptyText: { fontSize: 13.5, color: "var(--text-secondary)", margin: 0 } satisfies CSSProperties,
  list: { display: "flex", flexDirection: "column", gap: 6 } satisfies CSSProperties,
  noCallersToggle: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    marginTop: 10,
    padding: 0,
    background: "none",
    border: "none",
    cursor: "pointer",
    fontSize: 12.5,
    color: "var(--text-muted)",
    textAlign: "left",
  } satisfies CSSProperties,
  noCallersList: {
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
    margin: "8px 0 0",
    padding: 0,
    listStyle: "none",
  } satisfies CSSProperties,
  noCallersItem: {
    fontFamily: "var(--font-mono, monospace)",
    fontSize: 12,
    padding: "2px 6px",
    borderRadius: 4,
    background: "var(--bg-hover)",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
} as const;
