import type { CSSProperties } from "react";

/** Co-located styles for CreateConventionSkillModal. */
export const s = {
  content: { padding: "18px 24px 4px" } satisfies CSSProperties,
  banner: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "12px 16px",
    borderRadius: 8,
    background: "var(--accent-bg)",
    color: "var(--text-secondary)",
    fontSize: 13.5,
    lineHeight: 1.5,
    marginBottom: 18,
  } satisfies CSSProperties,
  bannerIcon: { color: "var(--accent)", flexShrink: 0 } satisfies CSSProperties,
  repo: { color: "var(--accent-text)", fontFamily: "var(--font-mono)" } satisfies CSSProperties,
  splitRow: {
    display: "inline-flex",
    padding: 3,
    gap: 3,
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    marginBottom: 16,
  } satisfies CSSProperties,
  splitBtn: (active: boolean): CSSProperties => ({
    padding: "5px 12px",
    borderRadius: 6,
    border: "none",
    cursor: "pointer",
    fontSize: 12.5,
    fontWeight: 500,
    background: active ? "var(--bg-hover)" : "transparent",
    color: active ? "var(--text-primary)" : "var(--text-muted)",
  }),
  tabs: {
    display: "flex",
    flexWrap: "wrap",
    gap: 4,
    marginBottom: 16,
    borderBottom: "1px solid var(--border)",
  } satisfies CSSProperties,
  tab: (active: boolean, valid: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: "7px 12px",
    background: "none",
    cursor: "pointer",
    fontSize: 13,
    fontWeight: 500,
    borderTop: "none",
    borderRight: "none",
    borderLeft: "none",
    borderBottom: `2px solid ${active ? "var(--accent)" : "transparent"}`,
    color: !valid ? "var(--crit)" : active ? "var(--text-primary)" : "var(--text-muted)",
    marginBottom: -1,
  }),
  tabCount: {
    fontSize: 11,
    padding: "0 6px",
    borderRadius: 99,
    background: "var(--bg-hover)",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  loading: { display: "flex", flexDirection: "column", gap: 12, paddingBottom: 16 } satisfies CSSProperties,
  footer: { display: "flex", alignItems: "center", gap: 8, width: "100%" } satisfies CSSProperties,
  footerNote: {
    flex: 1,
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 12.5,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
} as const;
