import type { CSSProperties } from "react";

export const s = {
  head: { padding: "14px 14px 8px" } satisfies CSSProperties,
  title: {
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  globs: {
    fontSize: 12,
    color: "var(--text-secondary)",
    marginTop: 3,
    fontFamily: "var(--font-mono)",
    overflowWrap: "anywhere",
  } satisfies CSSProperties,
  toolbar: { display: "flex", gap: 4, padding: "6px 10px 10px" } satisfies CSSProperties,
  syncBtn: (disabled: boolean): CSSProperties => ({
    width: 30,
    height: 30,
    display: "inline-grid",
    placeItems: "center",
    borderRadius: 6,
    border: "1px solid transparent",
    background: "transparent",
    color: "var(--text-secondary)",
    opacity: disabled ? 0.5 : 1,
    cursor: disabled ? "not-allowed" : "pointer",
  }),
  list: { flex: 1, minHeight: 0, overflowY: "auto", padding: "0 8px 8px" } satisfies CSSProperties,
  folder: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: "10px 8px 4px",
    fontSize: 11.5,
    fontWeight: 600,
    color: "var(--text-muted)",
    fontFamily: "var(--font-mono)",
    overflowWrap: "anywhere",
  } satisfies CSSProperties,
  emptyFolder: { padding: "2px 10px 4px 28px", fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  row: (selected: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
    textAlign: "left",
    padding: "7px 10px",
    borderRadius: 6,
    border: "1px solid transparent",
    background: selected ? "var(--bg-hover)" : "transparent",
    color: selected ? "var(--text-primary)" : "var(--text-secondary)",
    cursor: "pointer",
    fontSize: 13,
  }),
  name: {
    flex: 1,
    minWidth: 0,
    fontFamily: "var(--font-mono)",
    fontSize: 12.5,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  badge: { padding: "1px 6px", fontSize: 10.5 } satisfies CSSProperties,
} as const;
