import type { CSSProperties } from "react";

/** Co-located styles for IntentCard. */
export const s = {
  card: { marginBottom: 4 } satisfies CSSProperties,
  /* Collapsible header — mirrors SectionLabel's look, but is a button and
     drops the bottom margin while folded. */
  toggle: (open: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 10,
    width: "100%",
    padding: 0,
    marginBottom: open ? 14 : 0,
    background: "none",
    border: "none",
    cursor: "pointer",
    textAlign: "left",
  }),
  toggleIcon: { color: "var(--text-muted)" } satisfies CSSProperties,
  toggleTitle: {
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: "0.07em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  toggleRight: {
    marginLeft: "auto",
    display: "flex",
    alignItems: "center",
    gap: 8,
  } satisfies CSSProperties,
  chevron: (open: boolean): CSSProperties => ({
    color: "var(--text-muted)",
    transform: open ? "rotate(180deg)" : "none",
    transition: "transform 0.15s",
  }),
  summary: {
    fontSize: 15,
    fontStyle: "italic",
    color: "var(--text-primary)",
    lineHeight: 1.5,
    margin: "0 0 18px",
  } satisfies CSSProperties,
  columns: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 20,
    marginBottom: 16,
  } satisfies CSSProperties,
  column: { minWidth: 0 } satisfies CSSProperties,
  columnHeader: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    marginBottom: 8,
  } satisfies CSSProperties,
  inScopeIcon: { color: "var(--ok)" } satisfies CSSProperties,
  outOfScopeIcon: { color: "var(--crit)" } satisfies CSSProperties,
  list: {
    margin: 0,
    padding: 0,
    listStyle: "none",
    display: "flex",
    flexDirection: "column",
    gap: 6,
  } satisfies CSSProperties,
  listItem: {
    fontSize: 13.5,
    lineHeight: 1.5,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  emptyList: {
    fontSize: 13,
    color: "var(--text-muted)",
    margin: 0,
  } satisfies CSSProperties,
  sourcesSection: {
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: "var(--border)",
    paddingTop: 14,
    marginBottom: 4,
  } satisfies CSSProperties,
  sourcesTitle: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    marginBottom: 8,
  } satisfies CSSProperties,
  sourcesList: {
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
  } satisfies CSSProperties,
  sourceTag: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    fontSize: 11.5,
    padding: "3px 8px",
    borderRadius: 5,
    background: "var(--bg-hover)",
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  sourceTagUnavailable: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    fontSize: 11.5,
    padding: "3px 8px",
    borderRadius: 5,
    background: "var(--warn-bg)",
    color: "var(--warn)",
  } satisfies CSSProperties,
  missingContext: {
    fontSize: 12,
    color: "var(--warn)",
    marginTop: 8,
    marginBottom: 0,
  } satisfies CSSProperties,
  staleWarning: {
    fontSize: 12.5,
    color: "var(--warn)",
    marginTop: 12,
    marginBottom: 0,
  } satisfies CSSProperties,
  errorText: {
    fontSize: 12.5,
    color: "var(--crit)",
    marginTop: 12,
    marginBottom: 0,
  } satisfies CSSProperties,
  emptyText: {
    fontSize: 13.5,
    color: "var(--text-secondary)",
    margin: "0 0 4px",
  } satisfies CSSProperties,
  emptyHint: {
    fontSize: 12.5,
    color: "var(--text-muted)",
    margin: "0 0 14px",
  } satisfies CSSProperties,
  footer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginTop: 16,
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: "var(--border)",
  } satisfies CSSProperties,
  footerMeta: {
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
} as const;
